### ISSUE TITLE
using releases for datasets?

### ISSUE THREAD

**Issue by pachadotdev** [catmoez/Canadian-MPs-1994-present#1]
Hi!

Thx 4 making this publicly available

I saw you pushed a CSV file to the main repo. Have you considered using releases just for the data components of your project?

For example, https://github.com/pachadotdev/censo2017python uses https://github.com/pachadotdev/censo2017/archive/refs/tags/v0.4.zip, which is "separate" from the code, otherwise the repo would be bloated with 4 GB of datasets.

I hope to have suggested something useful if you plan to add more datasets here :D

**Comment by catmoez** [comment]
good idea, thank you
